image: Visual Studio 2019

branches:
  only:
  - master

build_script:
  - cmd: date /t
  - cmd: time /t
  - cmd: tzutil /g
  - cmd: dotnet restore AntlrExamples.sln
  - cmd: dotnet build AntlrExamples.sln
